### ISSUE TITLE
laod error

### ISSUE THREAD

**Issue by AsrielDreemurr6543** [sonicretro/SonLVL#11]
Every time i open a ini file it says load error and doesnt show anything everything seems fine but i cant load it please fix

**Comment by MainMemory** [comment]
Could you please be more specific? Are you opening the correct INI file (should be SonLVL.ini or something starting with SonLVL)? What exactly does the error message say? Can you paste the log?

**Comment by AsrielDreemurr6543** [comment]
It looks like SonLVL had some trouble loading your level.  If you have no idea what you're doing, please read the setup Guide. If you believe this is a bug in SonLVL, you can submit a Report. If you made a mistake or what to do something else, you can Cancel.  The error reported was: FileHotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?

**Comment by MainMemory** [comment]
http://info.sonicretro.org/SCHG_How-to:Set_Up_SonLVL
