### ISSUE TITLE
Windows Defender in Windows 11 says SonLVL.exe has a Trojan Malware

### ISSUE THREAD

**Issue by thecatfromthefuture** [sonicretro/SonLVL#111]
I dont have screenshots but the first time i was in panic 
i dont know why but SonLVL.exe created TEMP Files
and windows was reporting them has virus
 and later i found a report saying that its was containing Uwamson a.ml a variant of the Trojan Virus
now i am using Beta 5 , but can its be fixed?

**Comment by thecatfromthefuture** [comment]
so somewhone can prove that this not a malware and if its safe to disable my antivirus

**Comment by MainMemory** [comment]
It's not malware.

**Comment by thecatfromthefuture** [comment]
ok , but how do i open it now do i need to disable windows defender?
