### ISSUE TITLE
How do I edit title cards in SonLVL or in the INI Files (Not an issue)

### ISSUE THREAD

**Issue by hellointernetclass** [sonicretro/SonLVL#112]
Actually i love using SonLVL for my ROM Hacks but how i edit or change the Title Cards
like i wanted to replace Emerald Hill Zone to something like Techno Hill Zone or smth with the word Techno in it.
So how ? do i need a other program?

**Comment by Ralakimus** [comment]
SonLVL is for editing level layouts. Title cards are a separate thing. You'll need to find the sprite data for the title cards and edit them.
