### ISSUE TITLE
Bug with Green Hill 3

### ISSUE THREAD

**Issue by moonalien77** [sonicretro/SonLVL#12]
I have an issue with editing Green Hill Zone Act 3 in SonLVL. I don't know if it's a problem with the disassembly (GitHub version) or the software itself (SonLVL). The problem is that I can edit foreground objects just fine, but when I try to edit the objects, they always revert back to the way they were before. Green Hill Zone Acts 1 and 2 do not have this problem. I'll attach screenshots to demonstrate. First screen is view in software, second and third screens is what happens in game. Notice how all the items are still there (used the invincibility monitor from normal play to walk on the spikes to show the right hand side), but I was still able to clear out all the foreground elements, in spite of deleting all of the old objects and adding in new ones that do not show up. Is there something I'm doing wrong, something wrong with the program, or some sort of weird conflict going on with the game's code and the SonLVL program?
![sonlvl1](https://user-images.githubusercontent.com/31380856/29747558-e8989d16-8ad4-11e7-92fc-0d0e80d46df8.jpg)
![sonlvl2](https://user-images.githubusercontent.com/31380856/29747560-e8d2a704-8ad4-11e7-88cd-53fec7122b86.jpg)
![sonlvl3](https://user-images.githubusercontent.com/31380856/29747559-e8cf48a2-8ad4-11e7-8bc4-3e07c5b7d564.jpg)

**Comment by MainMemory** [comment]
My guess is you're editing REV00 but building REV01, or vice versa.

**Comment by moonalien77** [comment]
Just checked to compare and sure enough it seems to be building as a REV00, even though I intend to build the ROM from REV01. First shot is the direct dump from SonLVL (REV00), and second one is the direct ROM from Steam (REV01). Whatever SonLVL is building is REV00, though I am using the .ini files for REV01 specifically. Any easy fix to this problem? I'm brand new to the world of ROM modding/hacking.
![s1](https://user-images.githubusercontent.com/31380856/29747621-eee6757e-8ad6-11e7-8227-8ff6228f23ec.jpg)
![s2](https://user-images.githubusercontent.com/31380856/29747622-ef29211c-8ad6-11e7-9808-50d98ce21232.jpg)

**Comment by MainMemory** [comment]
Open sonic.asm and change Revision from 0 to 1.

**Comment by moonalien77** [comment]
Just changed the revision number from 0 to 1 in the asm. Works like a charm right now. Thank you very much for the help.
![revision fix](https://user-images.githubusercontent.com/31380856/29747894-2ac89826-8adf-11e7-9302-3c73183ea3a7.jpg)

**Comment by MainMemory** [comment]
No problem.
