### ISSUE TITLE
Error in SonLVL

### ISSUE THREAD

**Issue by Deannord** [sonicretro/SonLVL#13]
Please help me to fix this Program: SonLVL
Build Date: 09/13/2017 18:32:40
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "D:\Sonlvl\Sonic 1 2005 INIs\SonLVL.ini"...
Game type is S1.
Opening INI file "D:\Sonlvl\Sonic 1 2005 INIs\SonLVL.ini"...
Game type is S1.
Loading Green Hill Zone Act 1...
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz1.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   в System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   в System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   в SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 157
   в SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) в E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:строка 556
---> (Внутреннее исключение #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
Имя файла: '../pallet/sonic.bin'
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8ghz1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   в System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   в System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   в SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 157
   в SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) в E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:строка 556
---> (Внутреннее исключение #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
Имя файла: '../pallet/sonic.bin'
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz1.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
256x256 chunk file "../map256/GHZ.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   в System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   в System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   в SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 157
   в SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) в E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:строка 556
---> (Внутреннее исключение #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
Имя файла: '../pallet/sonic.bin'
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8ghz1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
256x256 chunk file "../map256/GHZ.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   в System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   в System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   в SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 157
   в SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) в E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:строка 556
---> (Внутреннее исключение #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
Имя файла: '../pallet/sonic.bin'
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()<---

Loading Green Hill Zone Act 1...
8x8 tile file "../artnem/8x8ghz1.bin" not found.
16x16 block file "../map16/GHZ.bin" not found.
8x8 tile file "../artnem/8x8ghz2.bin" not found.
FG layout file "../levels/ghz1.bin" not found.
Loading palette file "../pallet/sonic.bin"...
Source: 0 Destination: 0 Length: 16
256x256 chunk file "../map256/GHZ.bin" not found.
BG layout file "../levels/ghzbg.bin" not found.
FG layout file "../levels/ghz2.bin" not found.
FG layout file "../levels/ghz3.bin" not found.
FG layout file "../levels/ending.bin" not found.
System.AggregateException: Произошла одна или несколько ошибок. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   в System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   в System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   в SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 157
   в SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) в E:\AutoBuild\SonLVL\SonLVL\MainForm.cs:строка 556
---> (Внутреннее исключение #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
Имя файла: '../pallet/sonic.bin'
   в SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() в E:\AutoBuild\SonLVL\SonLVLAPI\LevelData.cs:строка 542
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()<---

**Comment by Leo40Git** [comment]
Make sure you're using the correct project files! From this error log, it seems you're trying to use the Sonic 1 Hivebrain disassembly project files with the Sonic 1 Git disassembly.

**Comment by Deannord** [comment]
Um,I Trying To Launch Original Sonic 1 rom,And The Same Error :/

**Comment by Leo40Git** [comment]
Oh, you can't edit ROMs with this tool! You need a disassembly to edit levels.

**Comment by Deannord** [comment]
Im only use a SonLVL,I dunno others tools

**Comment by Techokami** [comment]
No, what he means is, if you want to edit a level, you have to load [this](https://github.com/sonicretro/s1disasm) and not the original ROM; the disassembly is the original ROM but taken apart to be easier to edit.

**Comment by Clownacy** [comment]
![](https://i.imgur.com/x0WDgsO.png)

Why not read the guide, like it tells you to?

**Comment by Techokami** [comment]
He probably couldn't, I have a funny feeling English isn't his native language
