### ISSUE TITLE
Need Some Help..

### ISSUE THREAD

**Issue by Deannord** [sonicretro/SonLVL#14]
You Know How To Hack Sonic 1 On Speed? A ROM with XVI32 Or Other Tools (I Cant Hack With "Sonic Hacking Studio" Because Its Have 12 Trojan's),If You Know Tell It To Me,Big Thanks If You Help To Me.

**Comment by Leo40Git** [comment]
I... what? You cannot hack ROMs with SonLVL. You will need to get a disassembly for Sonic 1 if you want to edit its levels in SonLVL.

**Comment by Deannord** [comment]
Not with SonLVL

**Comment by Deannord** [comment]
With Hex Editor Or XVI32

**Comment by Techokami** [comment]
This is the issue tracker for SonLVL. If you're looking for help with something else, you've come to the wrong place.
