### ISSUE TITLE
LevelConverter: issues converting from Sonic CD's format

### ISSUE THREAD

**Issue by OrionNavattan** [sonicretro/SonLVL#148]
LevelConverter seems to have issues with some of Sonic CD's levels. From the handful of Devon's INIs that I tried, It output jumbled messes for PPZ 1 Past and Present, whereas WWZ 1 Present's chunk layout converted correctly, but it the background it generated was messed up, with a set of foreground chunks inserted in the middle. This occurred when converting to both Sonic 2 and Sonic 3K. Not sure what is going on, but I don't think that is what it is supposed to be doing.

**Comment by MainMemory** [comment]
It's likely that the levels ended up with more than 256 chunks after converting to 128x128.

**Comment by OrionNavattan** [comment]
That unfortunately does appear to be the case. So much for converting that game to use 128x128 chunks.

**Comment by MainMemory** [comment]
There's the old conversions qiuu did, where he adjusted the levels slightly to fit within the limits of S2.
