### ISSUE TITLE
Lava Reef Zone rock object layout support

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/SonLVL#15]
> That thing D.A. Garden mentioned. Apparently it's completely undocumented.

From what I remember, LRZ has these scenery objects, that are just rocks which help to make chunks blend together or something. They have their own layout files, which may or may not be the same format as regular object placement files.

**Comment by fredbronze** [comment]
It's more than that. Those objects are there to avoid a limitation of the VDP hardware: the cave tiles need to have low priority so Sonic appears in front of them, but that would make him also appear in front of any neighboring rocks, and you can't give the rocks high priority without creating some ugly square edges.

Anyway, the format is indeed similar to the regular object placement files, except the type ID comes before the X/Y coords apparently. The ID is then used to look up **word_1CBBE**, which contains 30 different sprite definitions ready to be written directly into the sprite table buffer.

So yeah, give me a ring if/when you want to figure this stuff out.

**Comment by MainMemory** [comment]
Fixed by 5f836a3.

**Comment by fredbronze** [comment]
And it only took half a year!

**Comment by fredbronze** [comment]
And it only took half a year!
