### ISSUE TITLE
Could not find file

### ISSUE THREAD

**Issue by MTEVEGITHUB** [sonicretro/SonLVL#153]
I've never had expirence with a sonic rom hack maker, and when I try to edit ghz act 1, it says it can't find something dealing with green hills water? Idk man. Writing this on mobile btw

**Comment by MTEVEGITHUB** [comment]
![Uploading 16904844156801119608025191532254.jpg…]()

**Comment by MTEVEGITHUB** [comment]
?

**Comment by MainMemory** [comment]
Your image didn't upload properly, please just copy and paste the text from the Bug Report dialog.

**Comment by MTEVEGITHUB** [comment]
I can't remeber that well, but I think it's ghzwater?
Also, for marble its the lava. Idk.

**Comment by MainMemory** [comment]
Can't you load the level again and show me the bug report text?

**Comment by MTEVEGITHUB** [comment]
The error reported was: DirectoryNotFoundException: Could not find a part of the path 'C:\Users\lisa\Desktop\Sonic 1 2005 disassembly\arturc\ghzwater bin.
The error reported was: DirectoryNotFoundException:

Could not find a part of the path

C:\Users\isa\Desktop\Sonic 1 2005

disassembalyartunc\mzlava1 bin

The error reported was: DirectoryNotFoundException Could not find a part of the path C\Users\lisa\Desktop\Sonic 1 2005 disassembalyartunc\sbzsmoke.bin

**Comment by MTEVEGITHUB** [comment]
Please take this note seriously, as I used Google lens.

**Comment by MTEVEGITHUB** [comment]
I've decided to do the tutorial on sonic retro again.

**Comment by MTEVEGITHUB** [comment]
It works! Sorry for wasting 86400+ seconds of your life.

**Comment by MainMemory** [comment]
That's alright, glad you got it sorted out.

**Comment by MTEVEGITHUB** [comment]
No problem! NOW im going to remove ALL OF THE RINGS!!!
