### ISSUE TITLE
Windows Defender flagging SonLVL as Trojan:Win32/Vagger!rfn

### ISSUE THREAD

**Issue by Techokami** [sonicretro/SonLVL#16]
Just updated to Windows 10 Fall Creators Update, and now Windows Defender has detected SonLVL.exe as Trojan:Win32/Vagger!rfn
I understand that this is a false positive but it should be looked into!

**Comment by MainMemory** [comment]
I already submitted it to MS, they verified it wasn't malware.

**Comment by Clownacy** [comment]
https://github.com/sonicretro/SonLVL/commit/c6baeedd988b1d7ed068e8ddcfc201a1d6eaa66e

Just posting this here to keep things all in one place: apparently this is the commit that caused these false flags?

**Comment by MainMemory** [comment]
Yeah, I did a bisect and tested each build with VirusTotal.com, and that's the first build that shows a whole bunch of flags.

**Comment by GerbilSoft** [comment]
This is also triggering at least Avast and McAfee.

I'm going to take a look at that commit over the weekend and see if I can reorganize the code in such a way that it stops triggering Hack Detection.

**Comment by maludasek** [comment]
MS Windows Defender found that trojan in Default.SFX file installed with Winrar downloaded from winrar.pl. Malwarebytes and Eset does not recognize it as a trojan.

**Comment by atkins2080** [comment]
Hi, I'm new here and also new to Sonlvl, I downloaded everything needed and ran the updater but was greeted with a not able to download update, which is the updated version of Sonlvl.
![screencap1](https://user-images.githubusercontent.com/37964983/38167836-23a890a6-350b-11e8-9c91-86e944a4cbd5.png)
![screencap2](https://user-images.githubusercontent.com/37964983/38167837-282bc80a-350b-11e8-864c-36b2c7ca0f6a.png)

**Comment by MainMemory** [comment]
You can download the program manually from https://mm.reimuhakurei.net/SonLVL/

**Comment by atkins2080** [comment]
Hi, got Sonlvl to update finally, one tiny problem is when I open the sonlvl.ini file I get this message.
![screencap3](https://user-images.githubusercontent.com/37964983/38168224-9a167844-3514-11e8-99ca-bc8ad5dd41ac.png)

**Comment by MainMemory** [comment]
I'm going to go ahead and guess that you haven't read the Guide.

**Comment by atkins2080** [comment]
Everything works now, I noticed the latest dissassembly doesn't have a split.bat contained.

**Comment by MainMemory** [comment]
So yeah I fixed this a while back by changing my local build path from E:\AutoBuild to E:\Programs. AVs are stupid.
