### ISSUE TITLE
Add tile compression method field to SonLVL.ini

### ISSUE THREAD

**Issue by Leo40Git** [sonicretro/SonLVL#18]
Don't have it locked to the game version!
Currently, it's impossible to edit Sonic 1 levels if you've ported the Sonic 2 art loader (I.E tile compression changed to Kosinski).

**Comment by MainMemory** [comment]
Um. This has been a feature since forever. Just put tilecmp=Kosinski before the first level definition.

**Comment by Leo40Git** [comment]
oh shit oops
sorry
