### ISSUE TITLE
Bug Or Glith Report

### ISSUE THREAD

**Issue by Leo714503** [sonicretro/SonLVL#180]
Hello, I was using the sonlvl tool quietly, I just came to report this bug here, it turns out that it was loading a level of sonic 3 & knuckles, I'll give you an example like launch base zone, so I go in and it detects it as a level of sonic 2 and it gives me this very long text

Program: SonLVL
Build Date: 10/16/2024 15:04:05
OS Version: Microsoft Windows NT 6.1.7600 Service Pack 1
Log:
Operating system: Microsoft Windows NT 6.1.7600 Service Pack 1
Opening INI file "C:\Users\usuario\Saved Games\SonLVL\skdisasm-master\skdisasm-master\SonLVL INI Files\AIZ\1.ini"...
Game type is S2.
Loading 03...
System.AggregateException: Se han producido uno o varios errores. ---> System.FormatException: Level must contain at least one Tiles file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelTiles() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 463
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   en System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   en System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   en SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 184
   en SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) en C:\Programs\SonLVL\SonLVL\MainForm.cs:línea 576
---> (Nº de excepción interna 0) System.FormatException: Level must contain at least one Tiles file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelTiles() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 463
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()<---

---> (Nº de excepción interna 1) System.FormatException: Level must contain at least one Blocks file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelBlocks() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 522
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()<---

---> (Nº de excepción interna 2) System.FormatException: Level must contain at least one Chunks file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelChunks() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 554
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()<---

---> (Nº de excepción interna 3) System.FormatException: Level must contain a Layout file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelLayout(String levelname) en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 627
   en SonicRetro.SonLVL.API.LevelData.<>c__DisplayClass70_0.<LoadLevel>b__0() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 184
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()<---

---> (Nº de excepción interna 4) System.FormatException: Level must contain at least one Palette file!
   en SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() en C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:línea 679
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()<---

**Comment by Leo714503** [comment]
evidence : 1
![evidence 1](https://github.com/user-attachments/assets/9640f2c3-6b67-4fb8-bec5-fa716940bf1e)
evidence : 2
![evidence 2](https://github.com/user-attachments/assets/16d40f8d-c112-4676-8ccb-d36854a5329d)

**Comment by MainMemory** [comment]
That's because you are loading an Object Definition file. Use one of the INI files with `SonLVL` in the name from the `SonLVL INI Files` folder.

**Comment by Leo714503** [comment]
> That's because you are loading an Object Definition file. Use one of the INI files with `SonLVL` in the name from the `SonLVL INI Files` folder.

Thank you for responding as quickly as possible and if that was the problem then with the message you left me when I read it I didn't understand it at first but I realized something that I hadn't noticed was that when I just opened the folder you mentioned there were some .ini called: S3SSEdit.ini SonLVL - S&K.ini SonLVL - S3.ini SonLVL.ini and finally SonPLN.ini and by chance I tried just to check if it worked with the .ini called SonLVL - S3.ini and it worked

**Comment by MainMemory** [comment]
* `SonLVL.ini` is for editing Sonic 3 & Knuckles
* `SonLVL - S3.ini` is for editing Sonic 3 Alone
* `SonLVL - S&K.ini` is for editing Sonic & Knuckles alone
* `S3SSEdit.ini` is for editing the Special Stages with S3SSEdit
* `SonPLN.ini` is for editing backgrounds and menus with SonPLN
