### ISSUE TITLE
An issue I found when editing the pallete in WFz (s2)

### ISSUE THREAD

**Issue by SuperSonicGames234** [sonicretro/SonLVL#20]
Program: SonLVL
Build Date: 11/25/2017 19:39:38
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "E:\Sonic Hacking\US2Hv2\sonic ultra engine\SonLVL INI Files\SonLVL.ini"...
Game type is S2.
Loading Emerald Hill Zone Act 1...
Loading 16x16 blocks from file "../mappings/16x16/EHZ.bin", using compression Kosinski...
Loading 8x8 tiles from file "../art/kosinski/EHZ_HTZ.bin", using compression Kosinski...
Loading palette file "../art/palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
Loading layout from file "../level/layout/EHZ_1.bin", using compression Kosinski...
Loading 128x128 chunks from file "../mappings/128x128/EHZ_HTZ.bin", using compression Kosinski...
Loading palette file "../art/palettes/EHZ.bin"...
Source: 0 Destination: 16 Length: 48
Loading layout from file "../level/layout/EHZ_2.bin", using compression Kosinski...
Loading layout from file "../level/layout/HTZ_1.bin", using compression Kosinski...
Loading layout from file "../level/layout/HTZ_2.bin", using compression Kosinski...
Loading object definition file "obj.ini".
Loading object definition file "objEHZ.ini".
Loading ObjectDefinition type S2ObjectDefinitions.Common.PathSwapper from "Common\PathSwapper.cs"...
Compiling code file...

**Comment by MainMemory** [comment]
Did your message get cut off?

**Comment by SuperSonicGames234** [comment]
I don't know... I also (somehow) can't replicate it... It happened when I opened WFz in the 2007 dissasembly using the inis in the updater... sorry for wasting your time...

**Comment by MainMemory** [comment]
Okay then.
