### ISSUE TITLE
"Enable Dragging" Button does not work

### ISSUE THREAD

**Issue by Pacguy64** [sonicretro/SonLVL#21]
Pretty self explanatory. The button can be toggled, but it has absolutely no effect.

**Comment by MainMemory** [comment]
Well, I tested all four (palette, chunks, blocks, tiles) of the buttons labeled "Enable Dragging", and as far as I can tell, they all work as advertised.

**Comment by Pacguy64** [comment]
Sorry, failed to notice that there are several of them in the UI. Kind of confusing.

**Comment by MainMemory** [comment]
I think it makes sense, it's always a button on the toolbar right above whatever it affects. I could combine them all into a single menu item, but then people might think it disables the dragging of objects.
