### ISSUE TITLE
Sonlvl doesn't work properly with chunks over $FF

### ISSUE THREAD

**Issue by Pacguy64** [sonicretro/SonLVL#28]
Obviously, S1/S2/S3K etc. don't actually use this, but Level Convertor can make valid chunk files like this. They open in Sonlvl, but chunks past $FF can't be directly interacted with; it will assume your selecting an earlier chunk. This means you can't edit, delete, or copy/paste over these overflowing chunks.

**Comment by MainMemory** [comment]
I'm reluctant to make any adjustments to allow SonLVL to edit chunk lists larger than 256, because you can't use a chunk list that long in the game. I may instead change LevelConverter to declare a failure if too many chunks are created.

**Comment by Pacguy64** [comment]
My goal with editing such a large chunk list was to try and whittle it down into $0-$FF range. There were a lot of chunks in the conversion that seemed identical, could easily be replaced with others, or could be remedied by decorational objects. The overgrown chunk list is a pain to work with, but its' better then nothing, as long as I can edit it.
