### ISSUE TITLE
Add proper support for sprite priority

### ISSUE THREAD

**Issue by fredbronze** [sonicretro/SonLVL#36]
Right now, SonLVL draws every sprite into a single layer, which is then drawn in front of the low foreground plane and either in front or behind the the high foreground plane depending on a menu option.

However, there are times in which it is desirable to allow sprites go both in front and behind the foreground plane; when this happens, the foreground tiles are set to high priority, and then the sprites' priority is set depending on whether the sprite should go in front or behind the foreground element.

Typically, SonLVL's "sprites above high plane" option is used to facilitate editing, revealing objects that might be obscured by sacrificing accuracy. In the situation described above, though, this approach isn't sufficient, as sprites with priority will be incorrectly obscured until we switch to the "inaccurate" mode.

My proposal is that when parsing sprite mappings, any sprite pieces which have the priority flag set should be output to a separate buffer, so that at render time SonLVL can honor the low FG -> low sprites -> high FG -> high sprites ordering.

Note that there must be a way to manually override the priority of an entire image in an object's definition, as there are objects that override the priority of their own mappings through code.

**Comment by MainMemory** [comment]
Oh, right, I fixed this when I rewrote the sprite format.
