### ISSUE TITLE
Build & Run should also save changes before launching the game in the emulator

### ISSUE THREAD

**Issue by alexandervrs** [sonicretro/SonLVL#4]
Build & Run should also save changes before launching the emulator so that it runs the game with the new changes. 

Currently you need to first Save the project manually and then hit F5 or click the menu item which is tedious, and often you can find yourself just running the game and see no changes only to be reminded later that you forgot to Save first.

**Comment by MainMemory** [comment]
F5 toggles the menu, it doesn't build and run the rom.
