### ISSUE TITLE
Multiple Issues Noticed in Object Definition Editor

### ISSUE THREAD

**Issue by TokyoScarab** [sonicretro/SonLVL#40]
I've recently been using SonLVL and have been liking the software but the Object Definition Editor seems to be very very picky.  One thing I've noticed right off the bat is that if you open a disassembly with SonLVL, then from that point on, you cannot open the same disassembly with the Object Definition Editor ever again.  Also there is a check in the UI that should be added when you're naming new images.  If you clear the entire field, it'll throw an error about the field being empty.  I'm sure this is something to do with it putting that data somewhere else in real time, but is just really annoying.  Another big issue is that the mappers for certain objects in the Sonic3&K disassembly don't get read right at all.  The two that I noticed this issue with are the springs and the bubble spawner mappers.  The spikes use the same graphics file as the springs, but the spike mapper works well.  So I'm not sure if this is an issue with the Object Editor or the S3K disassembly but it could be worked in I'm sure.
Spring:
Art:  ../General/Sprites/Level Misc/SpikesSprings.bin
Path: ../General/Sprites/Level Misc/Map - Spring.asm
Bubble Spawner:
Art: ../General/Sprites/Bubbles.bin
Path: ../General/Sprites/Map - Bubbler.asm

Another issue I ran into with the Object Editor is with the Offset parameter for when you're adding an image to an object.  The biggest issue is that you can't enter negative values as your offset.  You can, however alter the offset in the xml and it will load the negative offset appropriately but will throw errors if you do anything with said image.  I've been doing work adding stuff for Sonic 3&K and I'm not sure how previous Sonic games handled their graphics offsets, but a lot of objects in this game need the negative offset option and it would be amazing if you could work it in.  Even if you go beyond the bounds of the graphics file you're working in, it doesn't crash the program, so it would probably just be fine to remove that limitation.  Other than these issues, I've loved worked with your software and hope to see it improve even more as time goes on! :D

**Comment by TokyoScarab** [comment]
These  are all from working with the Sonic 3 & Knuckles disassembly located here:
https://github.com/sonicretro/skdisasm

**Comment by MainMemory** [comment]
The object definition editor has been discontinued. Also, Neo from Sonic Retro is already working on a comprehensive set of object definitions for the Sonic 3 & Knuckles disassembly.

**Comment by TokyoScarab** [comment]
Is there any way I can get in touch with this person?

**Comment by MainMemory** [comment]
https://twitter.com/freddybneo
