### ISSUE TITLE
Include ability to determine chunk count limit

### ISSUE THREAD

**Issue by ghost** [sonicretro/SonLVL#42]
I modified the level formats to handle smaller chunks, and with smaller chunks meaning that each takes up less space now. I want to be able to define a larger chunk count limit in the INI instead of dealing with the hardcoded 256 limit.

**Comment by MainMemory** [comment]
The editor is very much hardcoded to treat chunk indexes as bytes. In order to have more chunks, I would have to change everything that works with the layout data to use words instead.

**Comment by death-rapunzel** [comment]
This can be closed now.

**Comment by MainMemory** [comment]
Fixed in #69.
