### ISSUE TITLE
Application Error problems. Still having the same error!

### ISSUE THREAD

**Issue by MusaedRahman14** [sonicretro/SonLVL#49]
So i was using the SonLVL updater right? then when i was done i got the application so i went to the SonLVL.EXE all of a sudden it gave me an error!! So i would like MainMemory to fix the problem.

**Comment by MainMemory** [comment]
It is compatible with Windows 10. I use Windows 10. Please include more details in your error report.

**Comment by MusaedRahman14** [comment]
When ever i open the application it gave me an error. i don't know why.

**Comment by MusaedRahman14** [comment]
Hi sorry for waiting

**Comment by MusaedRahman14** [comment]
Is the SonLVL.log in the folder?

**Comment by MainMemory** [comment]
Depending on how far you got in the process, it will either be in SonLVL's folder or in the folder with the project files.

**Comment by MusaedRahman14** [comment]
I am in SonLVL's folder and i can't find it

**Comment by MainMemory** [comment]
Can you at least do a printscreen of the error message and paste it here? If there's a Report button, click it, then copy and paste the text in the text box it displays.

**Comment by MusaedRahman14** [comment]
Ok i will try.

**Comment by MusaedRahman14** [comment]
But when i open it the message goes very fast

**Comment by MusaedRahman14** [comment]
Ok i know how to catch it. i have to spam it

**Comment by MusaedRahman14** [comment]
OK I FOUND IT! it says "Insufficient system resources exist to complete the requested service."

**Comment by MusaedRahman14** [comment]
So what now?

**Comment by MusaedRahman14** [comment]
Are you there?

**Comment by MusaedRahman14** [comment]
Are you finding the problem?

**Comment by MusaedRahman14** [comment]
Hello are you responding or what!?

**Comment by MainMemory** [comment]
I can't do anything to solve the problem without more information. But it sounds like it's a problem on your end, not mine.

**Comment by MusaedRahman14** [comment]
That is the information! Even if I make a new one I can still get that problem!


Sent from Mail for Windows 10

**Comment by MainMemory** [comment]
Make a new what?

**Comment by MusaedRahman14** [comment]
Even if i make the new SonLVL.exe that would give me the error!

Sent from Mail for Windows 10

**Comment by MainMemory** [comment]
Is that all the error message says?

**Comment by MusaedRahman14** [comment]
YES!


Sent from Mail for Windows 10

**Comment by MainMemory** [comment]
Have you tried redownloading SonLVL?

**Comment by MusaedRahman14** [comment]
Yes i did. Lots of time

Sent from Mail for Windows 10

**Comment by MainMemory** [comment]
Do you have an anti-virus or anti-malware program running?

**Comment by MusaedRahman14** [comment]
My Mcafee expired for 30 days


Sent from Mail for Windows 10

**Comment by MainMemory** [comment]
I can't help you. All the message tells me is your computer is out of resources for something. I can't reproduce the error on my computer and I've tried every solution I can think of that might fix it.
