### ISSUE TITLE
Scrolling with the mousewheel doesn't work

### ISSUE THREAD

**Issue by alexandervrs** [sonicretro/SonLVL#5]
Scrolling with the mousewheel (and Shift + mousewheel for horizontal scroll) doesn't seem to work in the object panel and in the level editor panel

**Comment by MainMemory** [comment]
I don't think I ever said it was supposed to work. In fact I've specifically avoided implementing it because levels are primarily horizontal.

**Comment by alexandervrs** [comment]
Just reporting it. Though standard levels are mainly horizontal, people could always tweak them to be more vertical anyway, that was the point of the editor, no?
In any case you could invert horizontal & vertical scroll just for the level editor panel (or better have that as an option).

Though scrollbars in the other kinds of panels (Objects, Chunks, Layout Sections, etc) should work properly though since all you can do is scroll vertically and doing it with the mousewheel for desktop users is faster.
